-- SCA_ARCHIVE_METADATA {"archive_name": "archive_2026-07-24_22-06-31.sql", "program_version": "1.0.0", "archive_version": "1", "database_schema_version": "1", "created_at": "2026-07-24T19:06:31Z", "record_count": 43, "refuel_record_count": 43, "invoice_record_count": 0, "period_start": "2026-07-01", "period_end": "2026-07-02"}

-- Generated by SCA Fuel archive system

-- TABLE refuel

CREATE TABLE refuel (
	vehicle_id INTEGER, 
	current_odometer FLOAT NOT NULL, 
	liters FLOAT NOT NULL, 
	actual_percentage FLOAT NOT NULL, 
	created_at DATE NOT NULL, 
	is_excess BOOLEAN NOT NULL, 
	is_illogical BOOLEAN NOT NULL, 
	station VARCHAR, 
	id SERIAL NOT NULL, 
	is_synced BOOLEAN NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(vehicle_id) REFERENCES vehicle (id) ON DELETE CASCADE
)

;

INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (431, 128903.0, 39.0, 2.9839326702371842, '2026-07-01', FALSE, TRUE, 'محطة بورفؤاد', 325, TRUE, '2026-07-13T06:42:40.555861');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (284, 524305.0, 35.0, 9.776536312849162, '2026-07-01', FALSE, FALSE, 'محطة بورفؤاد', 328, TRUE, '2026-07-13T06:44:43.816502');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (362, 450199.0, 41.0, 13.666666666666666, '2026-07-01', FALSE, FALSE, 'محطة بورفؤاد', 329, TRUE, '2026-07-13T06:46:45.582394');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (326, 832809.0, 57.0, 10.634328358208956, '2026-07-02', FALSE, FALSE, 'محطة بورسعيد', 332, TRUE, '2026-07-13T06:47:47.649276');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (352, 499685.0, 40.0, 14.925373134328357, '2026-07-02', FALSE, FALSE, 'محطة بورفؤاد', 337, TRUE, '2026-07-13T07:03:06.548444');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (369, 464852.0, 51.0, 11.697247706422019, '2026-07-02', FALSE, FALSE, 'محطة بورفؤاد', 340, TRUE, '2026-07-13T07:04:08.639574');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (281, 664338.0, 24.0, 24.0, '2026-07-01', TRUE, FALSE, 'محطة بورفؤاد', 324, TRUE, '2026-07-13T06:42:39.105267');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (462, 360071.0, 60.0, 0.016663380277778552, '2026-07-01', FALSE, TRUE, 'محطة بورفؤاد', 327, TRUE, '2026-07-13T06:43:41.833855');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (339, 460322.0, 40.0, 7.905138339920949, '2026-07-02', FALSE, FALSE, 'محطة بورسعيد', 331, TRUE, '2026-07-13T06:47:46.880290');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (371, 692915.0, 29.0, 12.446351931330472, '2026-07-02', FALSE, FALSE, 'محطة بورسعيد', 334, TRUE, '2026-07-13T06:48:49.713631');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (394, 764950.0, 64.0, 18.6046511627907, '2026-07-02', FALSE, FALSE, 'محطة بورسعيد', 336, TRUE, '2026-07-13T06:58:59.164919');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (388, 778482.0, 44.0, 1.3161830690996112, '2026-07-01', FALSE, TRUE, 'محطة بورفؤاد', 326, TRUE, '2026-07-13T06:43:42.522693');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (366, 701424.0, 47.0, 12.600536193029491, '2026-07-02', FALSE, FALSE, 'محطة بورسعيد', 330, TRUE, '2026-07-13T06:47:48.433560');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (390, 510586.0, 24.0, 12.972972972972974, '2026-07-02', FALSE, FALSE, 'محطة بورسعيد', 333, TRUE, '2026-07-13T06:48:50.603996');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (377, 608865.0, 36.0, 16.822429906542055, '2026-07-02', TRUE, FALSE, 'محطة بورسعيد', 335, TRUE, '2026-07-13T06:56:57.446585');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (353, 435304.0, 21.0, 14.285714285714285, '2026-07-02', FALSE, FALSE, 'محطة بورفؤاد', 338, TRUE, '2026-07-13T07:03:07.341761');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (433, 83743.0, 30.0, 0.999000999000999, '2026-07-02', FALSE, TRUE, 'محطة بورفؤاد', 341, TRUE, '2026-07-13T07:04:09.338891');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (335, 746136.0, 55.0, 17.405063291139243, '2026-07-01', FALSE, FALSE, 'محطة بورفؤاد', 321, TRUE, '2026-07-13T06:41:36.398845');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (443, 85581.0, 24.0, 13.114754098360656, '2026-07-01', FALSE, FALSE, 'محطة بورفؤاد', 322, TRUE, '2026-07-13T06:41:37.159444');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (458, 345037.0, 40.0, 12.195121951219512, '2026-07-01', FALSE, FALSE, 'محطة بورفؤاد', 323, TRUE, '2026-07-13T06:41:37.920807');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (380, 269658.0, 12.0, 7.0588235294117645, '2026-07-01', FALSE, FALSE, 'محطة بورسعيد', 300, TRUE, '2026-07-13T06:32:14.652485');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (368, 524203.0, 37.0, 15.289256198347106, '2026-07-01', FALSE, FALSE, 'محطة بورسعيد', 301, TRUE, '2026-07-13T06:32:15.433579');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (344, 252636.0, 22.0, 29.72972972972973, '2026-07-01', TRUE, FALSE, 'محطة بورسعيد', 302, TRUE, '2026-07-13T06:32:16.548344');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (390, 510401.0, 49.0, 4.553903345724907, '2026-07-01', FALSE, TRUE, 'محطة بورسعيد', 303, TRUE, '2026-07-13T06:32:17.304593');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (371, 692520.0, 39.0, 13.0, '2026-07-01', FALSE, FALSE, 'محطة بورسعيد', 304, TRUE, '2026-07-13T06:33:18.588053');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (430, 70685.0, 43.0, 10.617283950617285, '2026-07-01', FALSE, FALSE, 'محطة بورسعيد', 305, TRUE, '2026-07-13T06:33:19.268510');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (394, 764606.0, 84.0, 18.22125813449024, '2026-07-01', FALSE, FALSE, 'محطة بورسعيد', 306, TRUE, '2026-07-13T06:33:19.958196');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (371, 692682.0, 21.0, 12.962962962962962, '2026-07-01', FALSE, FALSE, 'محطة بورسعيد', 307, TRUE, '2026-07-13T06:33:20.726528');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (369, 464416.0, 65.0, 15.402843601895736, '2026-07-01', FALSE, FALSE, 'محطة بورفؤاد', 308, TRUE, '2026-07-13T06:33:21.400858');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (410, 572703.0, 48.0, 11.851851851851853, '2026-07-01', FALSE, FALSE, 'محطة بورفؤاد', 309, TRUE, '2026-07-13T06:35:24.568135');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (459, 529994.0, 23.0, 16.19718309859155, '2026-07-01', FALSE, FALSE, 'محطة بورفؤاد', 310, TRUE, '2026-07-13T06:38:26.819223');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (421, 191476.0, 50.0, 11.627906976744185, '2026-07-01', FALSE, FALSE, 'محطة بورفؤاد', 311, TRUE, '2026-07-13T06:38:27.662210');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (353, 435157.0, 19.0, 12.925170068027212, '2026-07-01', FALSE, FALSE, 'محطة بورفؤاد', 312, TRUE, '2026-07-13T06:38:28.340077');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (361, 390107.0, 34.0, 8.740359897172237, '2026-07-01', FALSE, FALSE, 'محطة بورفؤاد', 313, TRUE, '2026-07-13T06:38:29.112749');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (345, 491924.0, 40.0, 13.60544217687075, '2026-07-01', FALSE, FALSE, 'محطة بورفؤاد', 314, TRUE, '2026-07-13T06:39:30.409480');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (356, 574407.0, 60.0, 13.157894736842104, '2026-07-01', FALSE, FALSE, 'محطة بورفؤاد', 315, TRUE, '2026-07-13T06:39:31.162913');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (382, 301885.0, 160.0, 19.11589008363202, '2026-07-01', FALSE, TRUE, 'محطة بورفؤاد', 316, TRUE, '2026-07-13T06:40:32.350209');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (294, 388350.0, 32.0, 10.666666666666668, '2026-07-01', FALSE, FALSE, 'محطة بورفؤاد', 317, TRUE, '2026-07-13T06:40:33.114007');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (316, 478236.0, 68.0, 22.74247491638796, '2026-07-01', FALSE, FALSE, 'محطة بورفؤاد', 318, TRUE, '2026-07-13T06:40:33.975597');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (301, 163469.0, 21.0, 17.796610169491526, '2026-07-01', FALSE, FALSE, 'محطة بورفؤاد', 319, TRUE, '2026-07-13T06:40:34.648349');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (410, 573091.0, 36.0, 9.278350515463918, '2026-07-01', FALSE, FALSE, 'محطة بورفؤاد', 320, TRUE, '2026-07-13T06:40:35.321534');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (348, 591912.0, 60.0, 16.997167138810198, '2026-07-02', FALSE, FALSE, 'محطة بورفؤاد', 339, TRUE, '2026-07-13T07:04:10.117565');
INSERT INTO "refuel" ("vehicle_id", "current_odometer", "liters", "actual_percentage", "created_at", "is_excess", "is_illogical", "station", "id", "is_synced", "updated_at") VALUES (440, 86453.0, 25.0, 13.227513227513226, '2026-07-02', FALSE, FALSE, 'محطة بورفؤاد', 342, TRUE, '2026-07-13T07:05:11.315518');

-- TABLE invoice

CREATE TABLE invoice (
	station VARCHAR NOT NULL, 
	start_date DATE NOT NULL, 
	end_date DATE NOT NULL, 
	created_at DATE NOT NULL, 
	invoice_number VARCHAR, 
	total_amount FLOAT NOT NULL, 
	items JSON, 
	prices JSON, 
	id SERIAL NOT NULL, 
	PRIMARY KEY (id)
)

;
